title: Abhinaba Saha
logo: /assets/img/Abhinaba Passport - Copy.jpg

description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/abhinaba-saha-4b54749b/">Linkd</a>
  <a href="https://github.com/AbhinabaSaha-git">Git</a>
  
  <br>   
  I'm working on Chatbot development, using RASA core and RASA NLP, 
  as well as python for all the action related to the automation and chatbot actions. 
  I am in the implementation team for cognizant automation center.
  <br>
  </p>



theme: jekyll-theme-minimal
