title: <p align="center"> Abhinaba Saha </p>
logo: /assets/img/Abhinaba_logo.jpg

description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/abhinaba-saha-4b54749b/">LinkedIn</a> |

  <br>   
  I'm working on Chatbot development, using RASA core and RASA NLP.
  <br>
  </p>


theme: jekyll-theme-minimal
