title: Abhinaba Saha
logo: /assets/img/Abhinaba Passport.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/abhinaba-saha-4b54749b/">LinkdIn</a>
  <a href="https://github.com/AbhinabaSaha-git">LinkdIn</a>
  <br>   
  I'm working on Chatbot development, using RASA core and RASA NLP.
  I am in the implementation team for cognizant automation.
  <br>
  </p>

theme: jekyll-theme-minimal
